spring.application.name=CardIdentifier
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/card
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.servlet.multipart.max-file-size=5MB
spring.jpa.defer-datasource-initialization=true