spring.application.name=CardIdentifier
#spring.jpa.hibernate.ddl-auto=update #use update when adding new information for tables. It will auto run the alter command
spring.jpa.hibernate.ddl-auto=validate
spring.servlet.multipart.max-file-size=5MB
spring.jpa.defer-datasource-initialization=true
server.port=8090